# Generated by Django 2.0.4 on 2018-05-02 21:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Codigo unico del evento', primary_key=True, serialize=False)),
                ('nombre', models.TextField(help_text='Entre el nombre del evento', max_length=80)),
                ('descripcion', models.TextField(help_text='Entre una descripcion breve del evento', max_length=1000)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duracion', models.DurationField()),
                ('imagen', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Exposicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_minima', models.IntegerField(default=0, verbose_name='Capacidad Minima')),
                ('cap_maxima', models.IntegerField(default=0, verbose_name='Capacidad Maxima')),
                ('evento_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Expositor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(help_text='Entre su cedula', max_length=11)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=256)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(blank=True, choices=[('a', 'activo'), ('i', 'inactivo')], default='a', help_text='Estado del expositivo', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='FechaEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.DurationField()),
                ('hora_final', models.DurationField()),
                ('evento_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Evento')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Codigo localidad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('edificio', models.CharField(max_length=50)),
                ('salon', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField(default=0, verbose_name='Capacidad de Asistentes')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Codigo localidad', primary_key=True, serialize=False)),
                ('cedula', models.CharField(help_text='Entre su cedula', max_length=11)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Codigo unico de la promocion', primary_key=True, serialize=False)),
                ('ciclo', models.TextField(help_text='Entre nombre del ciclo del evento', max_length=50)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='exposicion',
            name='expositor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Expositor'),
        ),
        migrations.AddField(
            model_name='exposicion',
            name='localidad_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Localidad'),
        ),
        migrations.AddField(
            model_name='evento',
            name='promo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Promocion'),
        ),
    ]
