# Generated by Django 2.0.4 on 2018-05-04 21:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(help_text='Entre su cedula', max_length=11)),
                ('nombre', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=10)),
                ('contacto', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50)),
                ('nota', models.TextField(max_length=256)),
                ('fecha', models.DateField(default=datetime.datetime.today, editable=False)),
                ('agente_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.AgentePago')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.today, editable=False)),
                ('agente_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.AgentePago')),
            ],
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='promo_id',
            new_name='promo',
        ),
        migrations.RenameField(
            model_name='exposicion',
            old_name='evento_id',
            new_name='evento',
        ),
        migrations.RenameField(
            model_name='exposicion',
            old_name='expositor_id',
            new_name='expositor',
        ),
        migrations.RenameField(
            model_name='exposicion',
            old_name='localidad_id',
            new_name='localidad',
        ),
        migrations.RenameField(
            model_name='fechaevento',
            old_name='evento_id',
            new_name='evento',
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(help_text='Entre una descripcion breve del evento', max_length=256),
        ),
        migrations.AlterField(
            model_name='evento',
            name='duracion',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='evento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(help_text='Entre el nombre del evento', max_length=80),
        ),
        migrations.AlterField(
            model_name='expositor',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fechaevento',
            name='fecha',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='ciclo',
            field=models.CharField(help_text='Entre nombre del ciclo del evento', max_length=50),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='fecha_cierre',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='registro',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Evento'),
        ),
        migrations.AddField(
            model_name='registro',
            name='participante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Participante'),
        ),
        migrations.AddField(
            model_name='recibo',
            name='registro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.Registro'),
        ),
    ]
